[package]
name = "masterarbeit-greedy"
version = "0.1.0"
edition = "2021"

[dependencies]
array2d = "0.3.2"
env_logger = "0.11.5"
log = "0.4.22"
petgraph = "0.6.5"
rayon = "1.10.0"
serde = {version = "1.0.206", features = ["derive"]}
serde_json = "1.0.124"
text_io = "0.1.12"
