[package]
name = "masterarbeit-greedy"
version = "0.1.0"
edition = "2021"

[dependencies]
array2d = "0.3.2"
petgraph = "0.6.5"
serde = {version = "1.0.206", features = ["derive"]}
serde_json = "1.0.124"
